### ISSUE TITLE
wir brauchen einen launcher

### ISSUE THREAD

**Issue by DerWe** [LeShoe/CorviOfChaos#11]
Es kann sich jemand, wenn er will, um einen Launcher kümmern. Z.b. einfach auf der Basis vom Tkinter. der tut dann die daten von der datenbank abfragen, den spieler einloggen und dann die daten an das Spiel übergeben. Das sind daten, wie z.B. -aktueller raum, -aktuelle Items, -aktuelle leben. Nebenbei brauchen wir natürlich auch die möglichkeit, ein neuen Account zu erstellen, und mit einem bestehenden die daten zu Laden.

**Comment by beckerfe** [comment]
Ich habe einen erstellt, der das Spiel startet, die Steuerung zeigt und einen Close-Button besitzt, Dennoch muss jemand aber noch das Design, die Größe etc. ändern.

**Comment by Vantary** [comment]
Ich arbeitete dran. Am Wochenende konnte ich aber von zuhause nicht auf die Datei zugreifen. Werde mich morgen darum kümmern an die Datei zu kommen und d

**Comment by Vantary** [comment]
Vergesst was ich geschrieben hab wollte den Kommentar eigentlich löschen
