### ISSUE TITLE
Perspektive Tafel/Uhr

### ISSUE THREAD

**Issue by LeShoe** [LeShoe/CorviOfChaos#5]
Nette Perspektive - so habe ich einen Klassenraum noch nie gesehen.

Aber wenn schon, denn schon - Uhr darf nicht rund, Tafel kein Rechteck sein.
Perspektive! Gimp kann das...

**Comment by strecklu** [comment]
Ja, mag sein, allerdings handelt es sich bei den beiden Bildern nur um Beispiele die im weiteren Verlauf ausgetauscht-und natürlich-überarbeitet werden

**Comment by LeShoe** [comment]
Dann wird sich dieses Ticket ja praktisch magisch von selbst schließen!

**Comment by strecklu** [comment]
Danke für Ihre Anfrage, 
ich hoffe wir konnten Ihrem Anliegen gerecht werden.
Bei weiteren Fragen bitte ein neues Ticket eröffnen.
MFG
Support

**Comment by giannizachos02** [comment]
Netter Support

**Comment by NoahFuckingHartig** [comment]
habe in den finalen versionen bereits die perspektiven angepasst (hab die tafeln allerdings so gelassen)
-> master/spiel/rooms/xy.png
