### ISSUE TITLE
Raumwechsel

### ISSUE THREAD

**Issue by giannizachos02** [LeShoe/CorviOfChaos#6]
Sehr geehrter Support,
da ich die Verbindung zwischen Raucherecke und dem Oberstufenraum vollendet habe, ist jetzt die Frage ob man von Raum zu Raum ohne eine Tür wechseln kann (?). 

Mit freundlichen Grüßen
Ioannis Zachos, aka giannizachos02

**Comment by strecklu** [comment]
Hallo,
Vorab vielen dank in dein Vertrauen in diesen Support.
Ja man kann auch ohne Tür von Raum zu Raum wechseln.

Ebenfalls bedanken wir uns für deine konstruktive Arbeit.
