### ISSUE TITLE
Menu Design 

### ISSUE THREAD

**Issue by Vantary** [LeShoe/CorviOfChaos#8]
Kann mir bitte einer der Designer einen Entwurf für das Menü machen? Ich benötige Fortsetzten, Hilfe, Beenden als Optionen. Für weitere Ideen bin ich offen. Natürlich müsst ihr auch das Hilfemenü designen. In diesem soll die Steuerung des Spiels erklärt werden (offensichtlich ist diese noch nicht fertig). Kann sich Jemand bitte dazu bereiterklären? Danke schonmal im vorraus!

**Comment by giannizachos02** [comment]
Sehr geehrter @Vantary ,
@NoahFuckingHartig ist in diesem Bereich ein echtes Genie. 
Er wird sich an diese Aufgabe wenden.

Mit freundlichen Grüßen
Ioannis Zachos, aka giannizachos02

**Comment by NoahFuckingHartig** [comment]
jo, ich werde mich darum kümmern
